BEGIN;

CREATE TABLE tags (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  name VARCHAR(80) NOT NULL UNIQUE,

  -- Used in URLs such as /blog/tag/postgresql.
  slug VARCHAR(100) NOT NULL UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;